Algoritmo "imparouparse"
// 
//  
// Descrição   : Esse algoritmo diz se o número é Par ou Impar
// Autor(a)    : Leticia Honorio Pereira
// Data atual  : 12/05/2021
Var
num: inteiro
Inicio
//entrada
escreval ("Digite um Número: ")
leia (num)

//processamento
se (num mod 2)= 1 entao

   escreval ("O número é IMPAR")

fimse

se (num mod 2)= 0 entao

   escreval ("O número é PAR")

fimse
Fimalgoritmo