Algoritmo "deznumerosinteiros"
// 
//  
// Descrição   : Este algoritmo le 10 numeros inteiros e no final apresenta a soma deles
// Autor(a)    : Leticia Honorio Pereira
// Data atual  : 20/08/2021
Var
valor,num,resul: inteiro

Inicio
//processamento

para num<- ate 10 faca
     escreval ("Digite o valor inicial: ")
     leia (valor)
     resul <- resul+valor
fimpara

//saida
escreval ("O resultado final é: ", resul)

Fimalgoritmo