Algoritmo "numerosimpares"
// 
//  
// Descrição   : este algoritmo gera e escreve os numeros impares entre 100 e 200
// Autor(a)    : Leticia Honorio Pereira
// Data atual  : 16/08/2021
Var
num, impar: inteiro

Inicio
escreval ("Digite o Número inicial: ")
leia (num)

limpatela

para impar de 100 ate 200 faca

      se (impar mod 2 <> 0) entao
      escreval ("Os numeros impares são: ", impar)
      fimse
      
fimpara


Fimalgoritmo