Algoritmo "Areadoretangulo"

//Este algoritmo calcula a area de um retangulo
//Autor: Leticia Honorio Pereira
//Data: 07/03/2021
Var

//Declaracao de variaveis

area,base,alt: real

Inicio

//entrada de dados

escreva("digite a base do retangulo")
leia (base)

escreva("digite a altura do retangulo")
leia (alt)

//processamento
area <- (base*alt)/2

//saida
escreva ("A area do retangulo e: ", area,"cm2")


Fimalgoritmo